Warm Daisy Tiger

High

# Collection token will get locked after shutdown cancellation

### Summary

The function `CollectionShutdown#cancel()` cancels the ongoing collection shutdown and delete the shutdown parameters for the collection, which causes voters can not reclaim collection token

### Root Cause

The storage variable [`_collectionParams[_collection]` is deleted](https://github.com/sherlock-audit/2024-08-flayer/blob/0ec252cf9ef0f3470191dcf8318f6835f5ef688c/flayer/src/contracts/utils/CollectionShutdown.sol#L403), which causes revert due to [arithmetic underflow](https://github.com/sherlock-audit/2024-08-flayer/blob/0ec252cf9ef0f3470191dcf8318f6835f5ef688c/flayer/src/contracts/utils/CollectionShutdown.sol#L369) in `CollectionShutdown#reclaimVote()` function

### Internal pre-conditions

1. An user needs to start a Collection shutdown
2. Users vote for the collection shutdown
3. The shutdown passes quorum and it is executable. It is also can be cancelled at this state

### External pre-conditions

_No response_

### Attack Path

1. An user calls `CollectionShutdown#start()`
2. Users vote using their collection token, through function `CollectionShutdown#vote()`
3. After quorum passes, an user calls `CollectionShutdown#cancel()` (with conditions satisfy checks in the function)
4. Voters call `CollectionShutdown#reclaimVote()`, which will always fail

### Impact

- Voted collection token for cancelled shutdowns get stuck in the contract

### PoC

Update the test `test_CanCancelShutdownFlow` in test file `CollectionShutdown.t.sol` as below:
```solidity
    function test_CanCancelShutdownFlow(uint _additionalAmount) public withQuorumCollection {
        // Confirm that we can execute with our quorum-ed collection
        assertCanExecute(address(erc721b), true);

        // Mint an amount that will allow us to start the cancel process. Our modifier
        // gives us the `MAX_SHUTDOWN_TOKENS` value, so any positive integer will suffice.
        vm.assume(_additionalAmount > 0);
        vm.assume(_additionalAmount < type(uint128).max);
        vm.prank(address(locker));
        collectionToken.mint(address(1), _additionalAmount);

        // Cancel our shutdown
        collectionShutdown.cancel(address(erc721b));

        // Now that we have cancelled the shutdown process, we should no longer
        // be able to execute the shutdown.
        assertCanExecute(address(erc721b), false);


        // Now we try to reclaim vote
        vm.startPrank(address(2));
        collectionShutdown.reclaimVote(address(erc721b));
    }
```

Run the test and console show the test fails due to underflow
```bash
Ran 1 test for test/utils/CollectionShutdown.t.sol:CollectionShutdownTest
[FAIL. Reason: panic: arithmetic underflow or overflow (0x11); counterexample: calldata=0x0cd0ba9b0000000000000000000000000000000000000000000000000000000000000003 args=[3]] test_CanCancelShutdownFlow(uint256) (runs: 0, Î¼: 0, ~: 0)
```

### Mitigation

- Add a flag for cancel status
- Update reclaimVote logic accordingly